name: floor_pretty_dto_example
description: Example for floor_pretty_dto.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: any

  floor_pretty_dto:
    git:
      url: git://github.com/BestAndroidTeam/floor_pretty_dto.git
      path: floor_pretty_dto
#  floor_pretty_dto:
#    path: ../floor_pretty_dto/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.4

  floor_pretty_dto_generator:
    git:
      url: git://github.com/BestAndroidTeam/floor_pretty_dto.git
      path: floor_pretty_dto_generator
#  floor_pretty_dto_generator:
#    path: ../floor_pretty_dto_generator/


flutter:
  uses-material-design: true