targets:
  $default:
    builders:
      floor_pretty_dto_generator:
        enabled: true

builders:
  floor_pretty_dto:
    target: ":floor_pretty_dto_generator"
    import: "package:floor_pretty_dto_generator/builder.dart"
    # The builder function name, which gets called on build/watch
    builder_factories: ["prettyDto"]
    # The 'partId' argument to 'SharedPartBuilder' is 'floor_pretty_dto'
    build_extensions: {".dart": [".floor_pretty_dto.g.part"]}

    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]