name: floor_pretty_dto
description: Pretty Dtos for floor.
version: 0.1.0
author: Ltei <xavier.peltier@outlook.com>
homepage: https://github.com/Ltei/floor_pretty_dto

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: 1.3.4
